FROM node as react-build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

ARG REACT_APP_NAME

ENV REACT_APP_NAME=$REACT_APP_NAME

RUN npm run build

FROM nginx

COPY --from=react-build /app/build /usr/share/nginx/html

